/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AttackRouteImport } from './routes/attack'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as TopologyRouteImport } from './routes/topology'
import { Route as ApiAnalyticsRouteImport } from './routes/api/analytics'
import { Route as ApiDevicesRouteImport } from './routes/api/devices'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as ApiPodsRouteImport } from './routes/api/pods'
import { Route as ApiZonesRouteImport } from './routes/api/zones'
import { Route as ApiSimulationAttackRouteImport } from './routes/api/simulation/attack'
import { Route as ApiSimulationCongestionRouteImport } from './routes/api/simulation/congestion'
import { Route as ApiSimulationFailureRouteImport } from './routes/api/simulation/failure'
import { Route as ApiSimulationResetRouteImport } from './routes/api/simulation/reset'
import { Route as ApiSimulationStartRouteImport } from './routes/api/simulation/start'
import { Route as ApiSimulationStateRouteImport } from './routes/api/simulation/state'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AttackRoute = AttackRouteImport.update({
  id: '/attack',
  path: '/attack',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const TopologyRoute = TopologyRouteImport.update({
  id: '/topology',
  path: '/topology',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsRoute = ApiAnalyticsRouteImport.update({
  id: '/api/analytics',
  path: '/api/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevicesRoute = ApiDevicesRouteImport.update({
  id: '/api/devices',
  path: '/api/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPodsRoute = ApiPodsRouteImport.update({
  id: '/api/pods',
  path: '/api/pods',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiZonesRoute = ApiZonesRouteImport.update({
  id: '/api/zones',
  path: '/api/zones',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSimulationAttackRoute = ApiSimulationAttackRouteImport.update({
  id: '/api/simulation/attack',
  path: '/api/simulation/attack',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSimulationCongestionRoute = ApiSimulationCongestionRouteImport.update({
  id: '/api/simulation/congestion',
  path: '/api/simulation/congestion',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSimulationFailureRoute = ApiSimulationFailureRouteImport.update({
  id: '/api/simulation/failure',
  path: '/api/simulation/failure',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSimulationResetRoute = ApiSimulationResetRouteImport.update({
  id: '/api/simulation/reset',
  path: '/api/simulation/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSimulationStartRoute = ApiSimulationStartRouteImport.update({
  id: '/api/simulation/start',
  path: '/api/simulation/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSimulationStateRoute = ApiSimulationStateRouteImport.update({
  id: '/api/simulation/state',
  path: '/api/simulation/state',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/attack': typeof AttackRoute
  '/logs': typeof LogsRoute
  '/security': typeof SecurityRoute
  '/topology': typeof TopologyRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/devices': typeof ApiDevicesRoute
  '/api/events': typeof ApiEventsRoute
  '/api/pods': typeof ApiPodsRoute
  '/api/zones': typeof ApiZonesRoute
  '/api/simulation/attack': typeof ApiSimulationAttackRoute
  '/api/simulation/congestion': typeof ApiSimulationCongestionRoute
  '/api/simulation/failure': typeof ApiSimulationFailureRoute
  '/api/simulation/reset': typeof ApiSimulationResetRoute
  '/api/simulation/start': typeof ApiSimulationStartRoute
  '/api/simulation/state': typeof ApiSimulationStateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/attack': typeof AttackRoute
  '/logs': typeof LogsRoute
  '/security': typeof SecurityRoute
  '/topology': typeof TopologyRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/devices': typeof ApiDevicesRoute
  '/api/events': typeof ApiEventsRoute
  '/api/pods': typeof ApiPodsRoute
  '/api/zones': typeof ApiZonesRoute
  '/api/simulation/attack': typeof ApiSimulationAttackRoute
  '/api/simulation/congestion': typeof ApiSimulationCongestionRoute
  '/api/simulation/failure': typeof ApiSimulationFailureRoute
  '/api/simulation/reset': typeof ApiSimulationResetRoute
  '/api/simulation/start': typeof ApiSimulationStartRoute
  '/api/simulation/state': typeof ApiSimulationStateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/attack': typeof AttackRoute
  '/logs': typeof LogsRoute
  '/security': typeof SecurityRoute
  '/topology': typeof TopologyRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/devices': typeof ApiDevicesRoute
  '/api/events': typeof ApiEventsRoute
  '/api/pods': typeof ApiPodsRoute
  '/api/zones': typeof ApiZonesRoute
  '/api/simulation/attack': typeof ApiSimulationAttackRoute
  '/api/simulation/congestion': typeof ApiSimulationCongestionRoute
  '/api/simulation/failure': typeof ApiSimulationFailureRoute
  '/api/simulation/reset': typeof ApiSimulationResetRoute
  '/api/simulation/start': typeof ApiSimulationStartRoute
  '/api/simulation/state': typeof ApiSimulationStateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/attack'
    | '/logs'
    | '/security'
    | '/topology'
    | '/api/analytics'
    | '/api/devices'
    | '/api/events'
    | '/api/pods'
    | '/api/zones'
    | '/api/simulation/attack'
    | '/api/simulation/congestion'
    | '/api/simulation/failure'
    | '/api/simulation/reset'
    | '/api/simulation/start'
    | '/api/simulation/state'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/attack'
    | '/logs'
    | '/security'
    | '/topology'
    | '/api/analytics'
    | '/api/devices'
    | '/api/events'
    | '/api/pods'
    | '/api/zones'
    | '/api/simulation/attack'
    | '/api/simulation/congestion'
    | '/api/simulation/failure'
    | '/api/simulation/reset'
    | '/api/simulation/start'
    | '/api/simulation/state'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/attack'
    | '/logs'
    | '/security'
    | '/topology'
    | '/api/analytics'
    | '/api/devices'
    | '/api/events'
    | '/api/pods'
    | '/api/zones'
    | '/api/simulation/attack'
    | '/api/simulation/congestion'
    | '/api/simulation/failure'
    | '/api/simulation/reset'
    | '/api/simulation/start'
    | '/api/simulation/state'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AttackRoute: typeof AttackRoute
  LogsRoute: typeof LogsRoute
  SecurityRoute: typeof SecurityRoute
  TopologyRoute: typeof TopologyRoute
  ApiAnalyticsRoute: typeof ApiAnalyticsRoute
  ApiDevicesRoute: typeof ApiDevicesRoute
  ApiEventsRoute: typeof ApiEventsRoute
  ApiPodsRoute: typeof ApiPodsRoute
  ApiZonesRoute: typeof ApiZonesRoute
  ApiSimulationAttackRoute: typeof ApiSimulationAttackRoute
  ApiSimulationCongestionRoute: typeof ApiSimulationCongestionRoute
  ApiSimulationFailureRoute: typeof ApiSimulationFailureRoute
  ApiSimulationResetRoute: typeof ApiSimulationResetRoute
  ApiSimulationStartRoute: typeof ApiSimulationStartRoute
  ApiSimulationStateRoute: typeof ApiSimulationStateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attack': {
      id: '/attack'
      path: '/attack'
      fullPath: '/attack'
      preLoaderRoute: typeof AttackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topology': {
      id: '/topology'
      path: '/topology'
      fullPath: '/topology'
      preLoaderRoute: typeof TopologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics': {
      id: '/api/analytics'
      path: '/api/analytics'
      fullPath: '/api/analytics'
      preLoaderRoute: typeof ApiAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/devices': {
      id: '/api/devices'
      path: '/api/devices'
      fullPath: '/api/devices'
      preLoaderRoute: typeof ApiDevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pods': {
      id: '/api/pods'
      path: '/api/pods'
      fullPath: '/api/pods'
      preLoaderRoute: typeof ApiPodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zones': {
      id: '/api/zones'
      path: '/api/zones'
      fullPath: '/api/zones'
      preLoaderRoute: typeof ApiZonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/simulation/attack': {
      id: '/api/simulation/attack'
      path: '/api/simulation/attack'
      fullPath: '/api/simulation/attack'
      preLoaderRoute: typeof ApiSimulationAttackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/simulation/congestion': {
      id: '/api/simulation/congestion'
      path: '/api/simulation/congestion'
      fullPath: '/api/simulation/congestion'
      preLoaderRoute: typeof ApiSimulationCongestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/simulation/failure': {
      id: '/api/simulation/failure'
      path: '/api/simulation/failure'
      fullPath: '/api/simulation/failure'
      preLoaderRoute: typeof ApiSimulationFailureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/simulation/reset': {
      id: '/api/simulation/reset'
      path: '/api/simulation/reset'
      fullPath: '/api/simulation/reset'
      preLoaderRoute: typeof ApiSimulationResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/simulation/start': {
      id: '/api/simulation/start'
      path: '/api/simulation/start'
      fullPath: '/api/simulation/start'
      preLoaderRoute: typeof ApiSimulationStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/simulation/state': {
      id: '/api/simulation/state'
      path: '/api/simulation/state'
      fullPath: '/api/simulation/state'
      preLoaderRoute: typeof ApiSimulationStateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AttackRoute: AttackRoute,
  LogsRoute: LogsRoute,
  SecurityRoute: SecurityRoute,
  TopologyRoute: TopologyRoute,
  ApiAnalyticsRoute: ApiAnalyticsRoute,
  ApiDevicesRoute: ApiDevicesRoute,
  ApiEventsRoute: ApiEventsRoute,
  ApiPodsRoute: ApiPodsRoute,
  ApiZonesRoute: ApiZonesRoute,
  ApiSimulationAttackRoute: ApiSimulationAttackRoute,
  ApiSimulationCongestionRoute: ApiSimulationCongestionRoute,
  ApiSimulationFailureRoute: ApiSimulationFailureRoute,
  ApiSimulationResetRoute: ApiSimulationResetRoute,
  ApiSimulationStartRoute: ApiSimulationStartRoute,
  ApiSimulationStateRoute: ApiSimulationStateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
